application: farmacias-de-turno
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.2"

builtins:
- django_wsgi: on

handlers:
- url: /static
  static_dir: static


